### ISSUE TITLE
No Releases / Version Tags

### ISSUE THREAD

**Issue by schmengler** [code4business/freeproduct#13]
The repository has no tags, so if you want to install a specific version using composer, you have to specify a commit hash, like `"dev-293021251bac87ae5849fd8ff5c080c743e1cb94"`. It would be great to have tags on the merge commits.

I'd suggest using [Semantic Versioning](http://semver.org/) but any kind of [version tags understood by Composer](https://getcomposer.org/doc/02-libraries.md#tags) are better than none.

**Comment by nkrambrock** [comment]
Changed version number to 1.0.0 in the code and created a corresponding tag: https://github.com/code4business/freeproduct/releases/tag/1.0.0
