### ISSUE TITLE
Gift product not showing

### ISSUE THREAD

**Issue by casperstaallekker** [code4business/freeproduct#25]
I am running this extension on my magento 1.9 webshop. If customers have a total order amount of 30 euros or higher they should have a free product:
![image](https://cloud.githubusercontent.com/assets/20662553/17138071/db2655e8-533e-11e6-95ff-47814ef13fbf.png)

The product is however not showing up in the shopping cart. Do you know how i can fix this?

**Comment by domeglic** [comment]
The discount amount is the qty of products added. Try setting it to 1 instead of 0.

**Comment by casperstaallekker** [comment]
Worked, thank you very much!
