### ISSUE TITLE
Order free product only

### ISSUE THREAD

**Issue by Skinwalker** [code4business/freeproduct#26]
When I try to order only the free product I don't make it to the checkout, because when I removed the last regular item the free product is removed as well.

Any idea how to fix that?

Edit:
I also can't add the free product to the cart only

**Comment by nkrambrock** [comment]
I am not sure I understand your question. Do you

1. want to get the free product free without buying anything else or
2. want to buy the free product regulary for the regular price?

The first case is not intended. freeproduct is offering a cart rule action that allows you to add a product depending on your cart. I did not try the second case for some time but I remember that it worked.

**Comment by nkrambrock** [comment]
No response until now and it looks like everything is working like intended.
