### ISSUE TITLE
Have fatal error when add bundle product as gift

### ISSUE THREAD

**Issue by ksbomj** [code4business/freeproduct#3]
For now have issue when setup bundle product as gift:
Fatal error: Call to a member function getValue() on a non-object in /var/magento/app/code/core/Mage/Bundle/Model/Product/Type.php on line 940

**Comment by domeglic** [comment]
Adding bundle types would require specifying the bundle options and selections. They only have IDs so that would make the configuration very dependent and also very problematic in case somebody changes that bundle product.
So we will not support types other than simple or virtual.
