### ISSUE TITLE
salesruleValidatorProcess uses $item->getStoreId might not be perfect

### ISSUE THREAD

**Issue by xqiu** [code4business/freeproduct#31]
For me, the following code in Freeproduct\Model\Observer.php salesruleValidatorProcess function

`$freeItem = static::_getFreeQuoteItem($rule->getId(), $sku, $item->getStoreId(), $qty);`

Need to be changed to 
`$freeItem = static::_getFreeQuoteItem($rule->getId(), $sku, $quote->getStoreId(), $qty);`

As I have a multi-lang store, I need the free product be the same language as the current quote language.

I'm not sure the reason why use $item->getStoreId, so I simply add the issue here.

**Comment by domeglic** [comment]
Well item and quote should have the same storeId actually so if it is not the same then seems like a Magento bug. But I see that we also use $quote in some places to get the store, having it the same way would be better. 
I will look into it.

**Comment by domeglic** [comment]
Commit e39dcff80113a9372df422ca0b4c8fcd5f1de58f should fix this problem now.

**Comment by xqiu** [comment]
Thanks!
