### ISSUE TITLE
Gift SKU not saving?

### ISSUE THREAD

**Issue by lbriet** [code4business/freeproduct#32]
Hey guys,

So I downloaded the repo and uploaded to server.

Created a new Shopping Cart Rule, selected the 'Add to Gift' option, set Discount Amount to 1, and entered Gift SKU. 

However, whenever I save the Shopping Cart rule, the Gift SKU never seems to be saved? Always shows up as a blank field afterwards.

Anyone have an idea as to how/why that could be happening?

**Comment by domeglic** [comment]
SKU is saved as a new field in the sales rule table. It could be that either the setup didn't run correctly or Magento is caching the table metadata.

**Comment by lbriet** [comment]
Check the database, field had correctly been added.

Some more digging showed the following however;

2017-11-14T16:39:49+00:00 ERR (3): 
exception 'C4B_Freeproduct_Exception_ProductNotSalable' with message 'C4B_Freeproduct: Gift product not saleable. Rule ID: 91, Gift SKU: , Store ID: 1' in /public_html/app/code/community/C4B/Freeproduct/Model/Observer.php:222

The free gift was (curiously) set as a configurable product - as the Readme clearly states, that won't do!

Apologies, should have double-checked. Thanks for the help @domeglic
