### ISSUE TITLE
Unable to download if gift is Downloadable Product

### ISSUE THREAD

**Issue by MatthijsIJ** [code4business/freeproduct#5]
I have tried to add a **downloadable product** as a free gift product. The downloadable product is displayed in the cart and also shows up as one of the Ordered Items after completing the checkout process. However, it is not displayed under My Downloadable Products in the Customers Account.

It seems that no information is stored in the `downloadable_link_purchased` and  `downloadable_link_purchased_item` database tables upon checkout.

More info on this issue can be found on [magento.stackexchange.com](http://magento.stackexchange.com/questions/52550/product-user-guide-manual-pdf-exclusively-available-as-download-in-customer-ac).

**Comment by nkrambrock** [comment]
It seems that there is something missing for this case in _getFreeQuoteItem in https://github.com/code4business/freeproduct/blob/master/app/code/community/C4B/Freeproduct/Model/Observer.php. My approach would be to compare the quoteItem that is gerated through _getFreeQuoteItem with the one that is created by putting the item into the cart directly. The difference should be the thing that needs to be done in _getFreeQuoteItem. Does this help?

**Comment by MatthijsIJ** [comment]
Hello Nikolai,

thanks for responding. But the downloadable product is added as a gift to the cart and also to the order after completing the purchase. I have checked the `sales_flat_quote_item` and `sales_flat_order_item` tables and the downloadable product is included as a free gift. This is not the problem. Reorder function is working fine too.

The only thing is that the download is missing in the list of "My Downloadable Products" in the Customer Account.

In `app/code/core/Mage/Downloadable/Model/Observer.php` there is a function called `saveDownloadableOrderItem($observer)`. I think this saves the purchased downloads to the `downloadable_link_purchased` and `downloadable_link_purchased_item` database tables. But this doesn't happen when the downloadable product is added as a free gift.

I'm not sure how to fix this and was hoping that you could do this as the developer of the module.

Thank you for looking into this!

**Comment by doctea** [comment]
Hi, was a solution ever found for this problem?

**Comment by domeglic** [comment]
I don't believe so. I will look into it this week.

**Comment by doctea** [comment]
Thanks domeglic!  I spent half a day on Friday testing it (issue definitely still exists) and trying to figure out how to work around it, without any joy.  If you'd like me to do any testing or further info then I'll help where I can!

**Comment by doctea** [comment]
Just to follow-up to my own post, there are several problems that crop up with my 'solution' above -- still looking for the proper way to do this!

**Comment by domeglic** [comment]
All other types have the same problem, they need additional information passed as the buy request like you found. I did recently implement this for a shop but the module became very complex and dependent on IDs.
So we will not support types other than simple or virtual to keep the module simple.
