### ISSUE TITLE
Cannot send headers error

### ISSUE THREAD

**Issue by Sharon831** [code4business/freeproduct#7]
Hello,

When I tried to add products into basket, there is an error message:

Cannot send headers; 
headers already sent in /var/www/.../app/code/community/C4B/Freeproduct/Model/Observer.php, line 1

How to fix this error?

**Comment by nkrambrock** [comment]
Can you be more specific? I am very sure that this is not happening in all cases. Please use an empty Magento System and try to reproduce the problem just installing freeproduct. Then explain all your steps and you system in detail. Thanks a lot!

**Comment by luckybonanza** [comment]
I can confirm, experiencing the same problem. I've been testing it out, whenever you click on Add to cart (any product) it gives you this error, then if you go back, the product is in your cart. Then when you go to cart and add the coupon code (for the gift) it gives you the same error, when you go back the gift is added though. So something is not working properly when clicking on Add Product and Applying the code inside the cart. 

Testing it on magento 1.9.1 

The exact message you get in the report is this: 

`a:5:{i:0;s:163:"Cannot send headers; headers already sent in /home/deb61256/domains/example.com/public_html/example/app/code/community/C4B/Freeproduct/Model/Observer.php, line 1";i:1;s:2042:"#0 /home/deb61256/domains/example.com/public_html/example/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Response/Http.php(107): Zend_Controller_Response_Abstract->setRedirect('http://www.exam...', 302)
#2 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Varien/Action.php(711): Mage_Core_Controller_Response_Http->setRedirect('http://www.exam...')
#3 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Varien/Action.php(689): Mage_Core_Controller_Varien_Action->setRedirectWithCookieCheck('checkout/cart', Array)
#4 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Checkout/controllers/CartController.php(95): Mage_Core_Controller_Varien_Action->_redirect('checkout/cart')
#5 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Checkout/controllers/CartController.php(595): Mage_Checkout_CartController->_goBack()
#6 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->couponPostAction()
#7 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('couponPost')
#8 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/deb61256/domains/example.com/public_html/example/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/deb61256/domains/example.com/public_html/example/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/deb61256/domains/example.com/public_html/example/index.php(87): Mage::run('', 'store')
#12 {main}";s:3:"url";s:32:"/example/checkout/cart/couponPost/";s:11:"script_name";s:16:"/example/index.php";s:4:"skin";s:6:"german";}`

**Comment by nkrambrock** [comment]
To me the files do not seem to have extra characters:
- https://github.com/code4business/freeproduct/blob/master/app/code/community/C4B/Freeproduct/Model/Consts.php
- https://github.com/code4business/freeproduct/blob/master/app/code/community/C4B/Freeproduct/Model/Observer.php

I am also sure that this problem is not happening on every machine; I know quite some people using it. Unless we have a clear step-by-step description how you can reproduce that on an otherwise empty Magento I cannot help.

**Comment by luckybonanza** [comment]
When you open those files in examdiff they do have those signs.

**Comment by nkrambrock** [comment]
Thanks for your comment and the pull requests afterwards. After double-checking I found out that the file was encoded in UTF8 and Magento is encoded in Ansi. So we changed that and we are going to change this for the other files next week.
